#config_version=5

keyboard:
  s:
    switch: s_start
  b:
    switch: s_buy_in
  l:
    switch: s_ball_launch
  1:
    switch: s_trough_1
    toggle: true
  8:
    switch: s_shooter_lane
    toggle: true
  x:
    switch: s_left_slingshot
  equals:
    switch: s_up
  minus:
    switch: s_down
  z:
    switch: s_flipper_lower_left
  /:
    switch: s_flipper_lower_right
  shift+1:
    switch: s_standup_1
  shift+2:
    switch: s_standup_2
  shift+3:
    switch: s_standup_3
  shift+4:
    switch: s_standup_4
  shift+5:
    switch: s_standup_5
  shift+8:
    switch: s_left_rollover
  shift+9:
    switch: s_center_rollover
  shift+0:
    switch: s_right_rollover
  h:
    event: start_high_score
  t:
    switch: s_plumb_bob
  shift+t:
    switch: s_slam_tilt
  ctrl+1:
    switch: s_left_coin
  ctrl+2:
    switch: s_center_coin
  ctrl+3:
    switch: s_right_coin
  ctrl+4:
    switch: s_fourth_coin
  ctrl+5:
    switch: s_esc
  ctrl+8:
    event: toggle_credit_play
  enter:
    switch: s_coin_door_closed
    toggle: true
  up:
    switch: s_up
  down:
    switch: s_down
  left:
    switch: s_esc
  right:
    switch: s_enter
