#config_version=6

mode_settings:
  display_delay_ms: 1000ms
  hurry_up_delay_ms: 0
  bonus_entries:
    # The order here is the order in which they will be shown
    - event: bonus_quests_completed
      score: 10_000
      # player_score_entry: net_quests_completed
      # skip_if_zero: false
    - event: bonus_avenger_runes
      score: 7000
      # player_score_entry: net_avenger_runes
      # skip_if_zero: false
    - event: bonus_training
      score: 100
      # player_score_entry: net_training_earned
      # skip_if_zero: false
