#config_version=6

mode_settings:
  display_delay_ms: 1000ms
  hurry_up_delay_ms: 0
  bonus_entries:
    # The order here is the order in which they will be shown
    - entry: big_stuff
      text: Big Stuff
      score: 10_000
      # player_score_entry: net_quests_completed
      # skip_if_zero: false
    - entry: bonus_too
      text: "Bonus, Too"
      score: 7000
      # player_score_entry: net_avenger_runes
      # skip_if_zero: false
    - entry: bonus_extra
      text: Extra Bonus
      score: 100
      # player_score_entry: nfu:

slide_player:
  mode_bonus_started: bonus
  bonus_start:
    bonus:
      action: update
      tokens:
        entry: initial
  bonus_entry:
    bonus:
      action: update

