#config_version=6
# Copyright 2021 Paradigm Tilt

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100


shots:
  bumper_shot_1:
    switch: s_switch_a
  bumper_shot_2:
    switch: s_switch_s



shot_groups:
  bumper_shots:
    shots: bumper_shot_1, bumper_shot_2


slide_player:
  mode_base_started: base
  s_switch_3_active:
    base:
      action: method
      method: show_text
      tokens:
        text: "Switch 3 Was Pressed!"
  s_switch_2_active:
    base_overlay:
      expire: 3s

variable_player:
  s_switch_1_active:
    score: 100
    bonus_multiplier: 1
  s_switch_2_active:
    score: 1000
    bonus_multiplier: 1

widget_player:
  slide_base_active:
    conditional_child_pools:
      slide: base
  s_switch_d_active:
    conditional_child_pools:
      action: remove
      slide: base
  mode_base_started:
    overlay_widget:
      slide: _overlay
      expire: 5s
      x: 100
      y: 500
