#config_version=5

ball_devices:

    bd_drain:
        ball_switches: s_outhole
        eject_coil: c_outhole
        eject_targets: bd_trough
        tags: drain, outhole

    bd_trough:
        ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_5
        eject_coil: c_ball_eject
        tags: trough, home