#config_version=5

smart_virtual:
  file_log: full

mpf:
  default_pulse_ms: 20

game:
  balls_per_game: 3
  max_players: 4

config:
- hardware.yaml
- keyboard.yaml
- autofire_coils.yaml
- flippers.yaml
- switches.yaml
- lights.yaml
- coils.yaml
- ball_devices.yaml
- machine.yaml
- modes.yaml
- player_vars.yaml
- playfields.yaml
- sequence_shots.yaml
- graphics.yaml
- sounds.yaml
- videos.yaml

widget_styles:
  text_default:
    font_name: psycha3
    font_size: 16
    adjust_top: 2
    adjust_bottom: 3
  space title huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    adjust_top: 3
    adjust_bottom: 3
  space title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    adjust_top: 2
    adjust_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    adjust_top: 1
    adjust_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    adjust_top: 2
    adjust_bottom: 3
  tall title:
    font_name: psycha3
    font_size: 20