#config_version=5

flippers: 
    left_flipper: 
        main_coil: c_flipper_left_main 
        hold_coil: c_flipper_left_hold 
        activation_switch: s_left_flipper
        
    right_flipper: 
        main_coil: c_flipper_right_main 
        hold_coil: c_flipper_right_hold 
        activation_switch: s_right_flipper